name = "selekt-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
MAX_PHOTOS_PER_SESSION = "50"
MAX_FILE_SIZE_MB = "30"
SESSION_TTL_DAYS = "7"
FREE_MONTHLY_STORAGE_MB = "2048"
PRO_MONTHLY_STORAGE_MB = "204800"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "selekt-photos"

[[kv_namespaces]]
binding = "USERS"
id = "732be010c98a44b4aa9832dc6e4674af"
